services:
  backend:
    build:
      context: ./backend

    container_name: abacontex-backend

    ports:
      - "${BACKEND_PORT}:3000"

    volumes:
      - ./backend:/app
      - /app/node_modules

    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ENVIRONMENT: ${VITE_ENVIRONMENT}

      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_BASE_URL: ${KEYCLOAK_BASE_URL}
      KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}

      KEYCLOAK_ADMIN_CLIENT_ID: ${KEYCLOAK_ADMIN_CLIENT_ID}
      KEYCLOAK_ADMIN_CLIENT_SECRET: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
      KEYCLOAK_FRONTEND_CLIENT_ID: ${KEYCLOAK_FRONTEND_CLIENT_ID}
      KEYCLOAK_TESTING_CLIENT_ID: ${KEYCLOAK_TESTING_CLIENT_ID}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}

      FRONTEND_URL: ${FRONTEND_URL}

    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_started

  frontend:
    build:
      context: ./frontend

    container_name: abacontex-frontend

    ports:
      - "${FRONTEND_PORT}:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_KEYCLOAK_URL: ${VITE_KEYCLOAK_URL}
      VITE_KEYCLOAK_REALM: ${VITE_KEYCLOAK_REALM}
      VITE_KEYCLOAK_CLIENT: ${VITE_KEYCLOAK_CLIENT}
      VITE_KEYCLOAK_REDIRECT_URI: ${VITE_KEYCLOAK_REDIRECT_URI}
      VITE_ENVIRONMENT: ${VITE_ENVIRONMENT}

    volumes:
      - ./frontend:/app
      - /app/node_modules

  postgres:
    image: postgres:17
    container_name: abacontex-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: UTC
      PGTZ: UTC

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.2

    container_name: abacontex-keycloak

    command:
      - start-dev
      - --import-realm

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_HTTP_ENABLED: "true"

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_HOSTED_DOMAIN: ${GOOGLE_HOSTED_DOMAIN}

      SMTP_DEBUG: ${SMTP_DEBUG}
      SMTP_STARTTLS: $SMTP_STARTTLS
      SMTP_AUTH: ${SMTP_AUTH}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      SMTP_SSL: ${SMTP_SSL}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

    ports:
      - "${KEYCLOAK_PORT}:8080"

    volumes:
      - ./keycloak/themes:/opt/keycloak/themes
      - ./keycloak/realm-export.dev.json:/opt/keycloak/data/import/realm.json
      - keycloak_data:/opt/keycloak/data

  mailpit:
    image: axllent/mailpit:latest

    container_name: abacontex-mailpit

    ports:
      - "${SMTP_PORT}:1025" # SMTP
      - "${MAILPIT_PORT}:8025" # Web UI

volumes:
  postgres_data:
  keycloak_data:
