export const ESTADOS_PEDIDOS = {
  PENDIENTE: 'PENDIENTE',
  EN_PRODUCCION: 'EN_PRODUCCION',
  LISTO_PARA_ENTREGAR: 'LISTO_PARA_ENTREGAR',
  COMPLETADO: 'COMPLETADO',
} as const;

export type EstadoPedido = (typeof ESTADOS_PEDIDOS)[keyof typeof ESTADOS_PEDIDOS];
