name: Frontend Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  frontend-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag
        id: tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build \
          -t ghcr.io/braianespanon/abacontex-frontend:${VERSION} \
          -t ghcr.io/braianespanon/abacontex-frontend:latest \
          ./frontend

      - name: Push image
        run: |
          docker push ghcr.io/braianespanon/abacontex-frontend:${VERSION}
          docker push ghcr.io/braianespanon/abacontex-frontend:latest